import { loader } from "fumadocs-core/source";
import { docs } from "../.source/server.ts";

/**
 * `docs` is generated by the `fumadocs-mdx` CLI from the Config API
 * collection declared in `source.config.ts`, persisted to `.source/` on
 * disk. Importing from there directly (rather than calling `defineDocs()`
 * from `fumadocs-mdx/macro` here) is what gives `tsc --noEmit` a real
 * `PageData` shape outside a live `next dev`/`next build` process.
 */
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
