import { llms, loader } from "fumadocs-core/source";
import { docs } from "../.source/server.ts";

/**
 * `docs` is generated by the `fumadocs-mdx` CLI from the Config API
 * collection declared in `source.config.ts`, persisted to `.source/` on
 * disk. Importing from there directly (rather than calling `defineDocs()`
 * from `fumadocs-mdx/macro` here) is what gives `tsc --noEmit` a real
 * `PageData` shape outside a live `next dev`/`next build` process.
 */
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});

/**
 * Renders docs pages as Markdown for LLMs/AI agents — `/llms.txt` (page
 * index), `/llms-full.txt` (every page concatenated), and per-page
 * `/docs/*.md`. `getText('processed')` reads the postprocessed Markdown
 * `source.config.ts`'s `includeProcessedMarkdown` exports per page, not
 * the raw MDX source, so JSX/component syntax in prose doesn't leak
 * through verbatim.
 */
export const docsLlms = llms(source, {
  renderPage: async (page) =>
    `# ${page.data.title} (${page.url})\n\n${await page.data.getText("processed")}`,
});
