import {
  BoldIcon,
  BrainIcon,
  BroomSparklesIcon,
  ChevronRightIcon,
  CodeIcon,
  ColumnsIcon,
  Heading1Icon,
  Heading2Icon,
  Heading3Icon,
  ImageIcon,
  ItalicIcon,
  LinkIcon,
  ListChecksIcon,
  ListIcon,
  ListOrderedIcon,
  Maximize2Icon,
  MessageSquareIcon,
  Minimize2Icon,
  MinusIcon,
  PaperclipIcon,
  PencilSparklesIcon,
  QuoteIcon,
  SparklesIcon,
  SpellCheckIcon,
  SquareDashedIcon,
  StrikethroughIcon,
  TableIcon,
  TypeIcon,
  VideoIcon,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  bold: BoldIcon,
  brain: BrainIcon,
  "broom-sparkles": BroomSparklesIcon,
  "chevron-right": ChevronRightIcon,
  code: CodeIcon,
  columns: ColumnsIcon,
  "heading-1": Heading1Icon,
  "heading-2": Heading2Icon,
  "heading-3": Heading3Icon,
  image: ImageIcon,
  italic: ItalicIcon,
  link: LinkIcon,
  "list-checks": ListChecksIcon,
  list: ListIcon,
  "list-ordered": ListOrderedIcon,
  "make-longer": Maximize2Icon,
  "make-shorter": Minimize2Icon,
  "maximize-2": Maximize2Icon,
  "message-square": MessageSquareIcon,
  "minimize-2": Minimize2Icon,
  minus: MinusIcon,
  paperclip: PaperclipIcon,
  "pencil-sparkles": PencilSparklesIcon,
  quote: QuoteIcon,
  sparkles: SparklesIcon,
  "spell-check": SpellCheckIcon,
  strikethrough: StrikethroughIcon,
  table: TableIcon,
  text: TypeIcon,
  video: VideoIcon,
};

export function resolveIcon(key?: string): LucideIcon {
  return (key && ICONS[key]) || SquareDashedIcon;
}
